"""add step timestamps

Revision ID: da4336c24e37
Revises: 3abd1076efc3
Create Date: 2026-10-10 13:06:18.478523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da4336c24e37'
down_revision: Union[str, Sequence[str], None] = '3abd1076efc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_steps', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('order_steps', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_steps', 'completed_at')
    op.drop_column('order_steps', 'started_at')
    # ### end Alembic commands ###
